### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by mihaistoie** [mihaistoie/histria-js#11]
## Top priority
- [x] Composition one to one
- [x] Composition one to many
- [x] Reference one to one
- [x] Aggregations
- [x] Non persistent view
- [x] Persistence interface

## To analyse
* Json and Json patch
* Rest api on ObjectTransaction
